### ISSUE TITLE
ordercss: command not found

### ISSUE THREAD

**Issue by paulrosen** [steveswork/ordercss#1]
I did this in my project:
```
npm i -D @webkrafters/ordercss
```
I see the change to package.json. I did `npm install` just to be safe.

I expected to be able to type `ordercss` but when I did I get `bash: ordercss: command not found`.

Is there one more step?

**Comment by steveswork** [comment]
@paulrosen, pls install it globally to run it directly.
`npm i -g @webkrafters/ordercss`.

When installed without the -g flag, it runs as an npm script.
